version: '2'

# docker network inspect fmedel_network
# docker network create fmedel_network

networks:
  distribuida:
    external:
      name: fmedel_network

#Capa logica
services:
  api:
    build:
      context: ./api
      dockerfile: api.dockerfile
    volumes:
      - ./api:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8085:8085"
    links:
      - postgres
    networks:
      - distribuida

# Capa de persistencia
  postgres:
    build:
      context: ./bd
      dockerfile: Dockerfile
    ports:
      - 8082:5432
    environment:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: docker
    networks:
      - distribuida
#Capa de presentacion
  web:
    build:
      context: ./angular
      dockerfile: web.dockerfile
    ports:
      - 8081:80
    links:
      - api
    networks:
      - distribuida
