version: '2'

# docker network inspect fmedel_network
# docker network create fmedel_network

networks:
  distribuida:
    external:
      name: fmedel_network

services:
  web:
    build:
      context: .
      dockerfile: api.dockerfile
    volumes:
      - ./api:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8085:8085"
    links:
      - postgres


# Capa de persistencia
  postgres:
    build:
      context: ./bd
      dockerfile: Dockerfile
    ports:
      - 8082:5432
    environment:
      POSTGRES_USER : docker
      POSTGRES_PASSWORD : docker
      POSTGRES_DB : docker
