version: '2'
networks:
  distribuida:
    external:
      name: fmedel_network

services:
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes_from:
      - app
    ports:
      - 8082:80
volumes:
  dbdata:
