version: '2'

# docker network inspect fmedel_network
# docker network create fmedel_network

networks:
  distribuida:
    external:
      name: fmedel_network

services:
  postgres:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
