version: '2'

networks:
  distribuida:
    external:
      name: fmedel_network

services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8085:8085"
